site_name: arkIQ Documentation
site_description: Documentation for arkIQ IoT data management and alerting. 
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Verdana
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  logo: "https://thearkiq.com/wp-content/uploads/2024/03/arkIQ-Horizontal-TM-PNG-768x290.png"
  favicon: "https://media.licdn.com/dms/image/v2/D4E0BAQGm_K9hKOC6iA/company-logo_200_200/B4EZXIsZm.H0AI-/0/1742828837776/arkiq_logo?e=2147483647&v=beta&t=s-mwQWrz3zXGHuindYjJPvLAkCWT5rPnCRMuShekDI8"

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Services:
      - Auth Service: services/auth.md
      - IoT Data Service: services/iot-data.md
      - Alerting Service: services/alerting.md